apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-root
spec:
  selector:
    matchLabels:
      app: vulnerable-root
  template:
    metadata:
      labels:
        app: vulnerable-root
    spec:
      containers:
      - name: vulnerable-root
        image: nginx:1.21.6 # Specify a fixed image tag
        securityContext:
          runAsNonRoot: true # root user
          privileged: false # privilege escalation
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true # Make root filesystem read-only
          runAsUser: 10001 # User ID > 10000
          runAsGroup: 10001 # Group ID > 10000
          capabilities:
            drop:
            - ALL # Drop all capabilities
          seccompProfile:
            type: RuntimeDefault # Use RuntimeDefault seccomp profile
        ports:
        - containerPort: 8080 # Use a port >= 1024
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
